Update update_changelog.yml

diff --git a/.github/workflows/update_changelog.yml b/.github/workflows/update_changelog.yml
--- a/.github/workflows/update_changelog.yml
+++ b/.github/workflows/update_changelog.yml
@@ -33,36 +33,39 @@ jobs:
       - name: Get merged PRs
         id: pr-list
         run: |
-          TYPE="${{ github.event.inputs.type }}"
-          START="${{ github.event.inputs.start }}"
-          BRANCH="${GITHUB_REF_NAME}"
+            TYPE="${{ github.event.inputs.type }}"
+            START="${{ github.event.inputs.start }}"
+            BRANCH="${GITHUB_REF_NAME}"
+            
+            echo ${{ secrets.YDBOT_TOKEN }} > token.txt
+            export GH_TOKEN=$(cat token.txt)
+            gh auth login --with-token       
+            echo `gh auth status`
+            
+            echo "::notice:: branch = ${GITHUB_REF_NAME}, start = $START"
 
-          echo "::notice:: branch = ${GITHUB_REF_NAME}, start = $START"
-          echo ${{ secrets.YDBOT_TOKEN }} > token.txt
-          gh auth login --with-token < token.txt
-          gh ayth status
-          if [ "$TYPE" == "date" ]; then
-            echo "Getting PRs since date: $START"
-            PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergedAt >= \"$START\") | {id: .number}" | jq -c -s ".")
-          elif [ "$TYPE" == "tag" ]; then
-            echo "Fetching tags from remote"
-            git fetch --tags
-            echo "Getting PRs since tag: $START"
-            COMMIT=$(git rev-list -n 1 $START)
-            PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergeCommit.oid >= \"$COMMIT\") | {id: .number}" | jq -c -s ".")
-          elif [ "$TYPE" == "commit" ]; then
-            echo "Getting PRs since commit: $START"
-            PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergeCommit.oid >= \"$START\") | {id: .number}" | jq -c -s ".")
-          else
-            echo "::error::Invalid type: $TYPE"
-            exit 1
-          fi
-
-          if [ -z "$PRS" ]; then
-            PRS="[]"
-          fi
-          echo "$PRS" > prs.json
-          echo "prs=$PRS" >> "$GITHUB_OUTPUT"
+            if [ "$TYPE" == "date" ]; then
+              echo "Getting PRs since date: $START"
+              PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergedAt >= \"$START\") | {id: .number}" | jq -c -s ".")
+            elif [ "$TYPE" == "tag" ]; then
+              echo "Fetching tags from remote"
+              git fetch --tags
+              echo "Getting PRs since tag: $START"
+              COMMIT=$(git rev-list -n 1 $START)
+              PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergeCommit.oid >= \"$COMMIT\") | {id: .number}" | jq -c -s ".")
+            elif [ "$TYPE" == "commit" ]; then
+              echo "Getting PRs since commit: $START"
+              PRS=$(gh pr list --state merged --json number,title,baseRefName,mergedAt --jq ".[] | select(.baseRefName == \"$BRANCH\" and .mergeCommit.oid >= \"$START\") | {id: .number}" | jq -c -s ".")
+            else
+              echo "::error::Invalid type: $TYPE"
+              exit 1
+            fi
+  
+            if [ -z "$PRS" ]; then
+              PRS="[]"
+            fi
+            echo "$PRS" > prs.json
+            echo "prs=$PRS" >> "$GITHUB_OUTPUT"
 
       - name: Debug PR list output
         run: |
